In [2]:
import pandas as pd
import numpy as np
from pyomo.environ import *

In [3]:
distance_matrix = pd.read_csv('../../data/dataset/Distance_Matrix.csv')
biomass_hist = pd.read_csv('../../data/dataset/Biomass_History.csv')

distance_matrix.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,2408,2409,2410,2411,2412,2413,2414,2415,2416,2417
0,0,0.0000,11.3769,20.4557,38.1227,45.3810,54.9915,78.6108,118.6750,102.6639,...,683.8771,687.6310,697.3246,669.3962,667.6788,665.5775,662.0291,665.9655,673.2073,681.4235
1,1,11.3769,0.0000,9.0788,28.9141,36.1724,45.7829,69.4022,78.2329,93.4553,...,681.6295,685.3833,695.0769,667.1485,665.4311,663.3298,659.7815,663.7178,670.9596,679.1758
2,2,20.4557,9.0788,0.0000,22.3791,29.6374,39.2478,62.8671,71.6979,86.9203,...,682.2323,685.9861,695.6796,667.7513,666.0339,663.9326,660.3843,664.3206,671.5623,679.7786
3,3,38.1227,28.9141,22.3791,0.0000,11.8343,23.5413,41.8396,50.6703,65.8927,...,681.4226,685.1765,694.8701,666.9417,665.2243,663.1230,659.5746,663.5110,670.7528,678.9690
4,4,45.3810,36.1724,29.6374,11.8343,0.0000,11.7070,24.3986,33.2293,53.9901,...,663.9816,667.7355,677.4291,649.5007,647.7833,645.6820,642.1336,646.0700,653.3118,661.5280

In [4]:
distance_matrix.drop(['Unnamed: 0'], axis=1, inplace=True)
distance_matrix = np.array(distance_matrix)
distance_matrix

array([[  0.    ,  11.3769,  20.4557, ..., 665.9655, 673.2073, 681.4235],
       [ 11.3769,   0.    ,   9.0788, ..., 663.7178, 670.9596, 679.1758],
       [ 20.4557,   9.0788,   0.    , ..., 664.3206, 671.5623, 679.7786],
       ...,
       [663.7748, 661.5271, 662.1298, ...,   0.    ,  14.2423,  22.4586],
       [671.0165, 668.7688, 669.3715, ...,  14.2423,   0.    ,  12.4741],
       [679.2328, 676.9851, 677.5878, ...,  22.4586,  12.4741,   0.    ]])

In [5]:
biomass_hist.head()

,Index,Latitude,Longitude,2010,2011,2012,2013,2014,2015,2016,2017
0,0,24.66818,71.33144,8.475744,8.868568,9.202181,6.023070,10.788374,6.647325,7.387925,5.180296
1,1,24.66818,71.41106,24.029778,28.551348,25.866415,21.634459,34.419411,27.361908,40.431847,42.126945
2,2,24.66818,71.49069,44.831635,66.111168,56.982258,53.003735,70.917908,42.517117,59.181629,73.203232
3,3,24.66818,71.57031,59.974419,80.821304,78.956543,63.160561,93.513924,70.203171,74.536720,101.067352
4,4,24.66818,71.64994,14.653370,19.327524,21.928144,17.899586,19.534035,19.165791,16.531315,26.086885

In [6]:
b_2010 = np.array(biomass_hist['2010'])

In [7]:
b_2010

array([8.47574425e+00, 2.40297775e+01, 4.48316345e+01, ...,
       3.94147040e-02, 2.71922016e+00, 6.21228158e-01])

In [8]:
num_locations = 2418
num_depots_max = 25
num_refineries_max = 5
harvest = b_2010 # List of harvest amounts at each location
#distance_matrix  2418x2418 distance matrix
cap_depot = 20000
cap_refinery = 100000

# Create a concrete model
model = ConcreteModel()

In [9]:

# Index sets
model.locations = RangeSet(1, num_locations)
model.depots = RangeSet(1, num_locations)  # We assume all locations can be potential depots
# model.refineries = RangeSet(1, num_refineries_max)
model.refineries = RangeSet(1, num_locations) # We assume all locations can be potential refineries

# Decision variables
model.depots_used = Var(model.depots, within=Binary)
model.refineries_used = Var(model.refineries, within=Binary)
model.harvest_flow = Var(model.locations, model.depots, within=NonNegativeReals)
model.pellet_flow = Var(model.depots, model.refineries, within=NonNegativeReals)
# model.under_utilization_cost = Var(model.depots, within=NonNegativeReals)
# model.under_utilization_cost_refineries = Var(model.refineries, within=NonNegativeReals)
model.pellet_flow_active = Var(model.depots, model.refineries, within=Binary)  # Binary variable indicating active pellet flow

In [10]:

# Objective function
def objective_rule(model):
    return (
        0.001*sum(distance_matrix[i-1][j-1] * model.harvest_flow[i, j] for i in model.locations for j in model.depots) +
        0.001*sum(distance_matrix[j-1][k-1] * model.pellet_flow[j, k] for j in model.depots for k in model.refineries) +
        sum(cap_depot - model.harvest_flow[i, j] for i in model.locations for j in model.depots) +  # Under-utilization cost for depots
        sum(cap_refinery - model.pellet_flow[j, k] for j in model.depots for k in model.refineries)   # Under-utilization cost for refineries
        # sum(cap_refinery * (1 - model.refineries_used[k]) for k in model.refineries)  # Under-utilization cost for unused refineries -->redundant
    )
model.objective = Objective(rule=objective_rule, sense=minimize)

In [ ]:

# Constraints
def max_depots_constraint_rule(model):
    return sum(model.depots_used[j] for j in model.depots) <= num_depots_max
model.max_depots_constraint = Constraint(rule=max_depots_constraint_rule)

# Constraint for maximum number of refineries
def max_refineries_constraint_rule(model):
    return sum(model.refineries_used[k] for k in model.refineries) <= num_refineries_max
model.max_refineries_constraint = Constraint(rule=max_refineries_constraint_rule)

def harvest_supply_constraint_rule(model, i):
    return sum(model.harvest_flow[i, j] for j in model.depots) <= harvest[i-1]
model.harvest_supply_constraint = Constraint(model.locations, rule=harvest_supply_constraint_rule)

# Constraint for pellets flow balance
def pellet_flow_balance_rule(model, j):
    return (
        sum(model.pellet_flow[j, k] for k in model.refineries) ==
        sum(model.harvest_flow[i, j] for i in model.locations)
    )
model.pellet_flow_balance_constraint = Constraint(model.depots, rule=pellet_flow_balance_rule)

def flow_binary_relation_rule(model, i, j):
    """
    This constraint ensures that if a depot is used (the binary variable is 1), 
    the corresponding harvest flow can be non-zero, but if a depot is not used (the binary variable is 0), the corresponding harvest flow must be zero.
    """
    return model.harvest_flow[i, j] <= model.depots_used[j] * harvest[i-1]
model.flow_binary_relation_constraint = Constraint(model.locations, model.depots, rule=flow_binary_relation_rule)


def pellet_flow_binary_relation_rule(model,i, j, k):
    return model.pellet_flow[j, k] <= model.refineries_used[k] * sum(model.harvest_flow[i, j] for i in model.locations)
model.pellet_flow_binary_relation_constraint = Constraint(model.locations, model.depots, model.refineries, rule=pellet_flow_binary_relation_rule)


def max_utilization_constraint_rule(model, j):
    return sum(model.harvest_flow[i, j] for i in model.locations) <= cap_depot
model.max_utilization_constraint = Constraint(model.depots, rule=max_utilization_constraint_rule)


# Constraint for maximum utilization of a refinery
def max_utilization_refineries_constraint_rule(model, k):
    return sum(model.pellet_flow[j, k] for j in model.depots) <= cap_refinery
model.max_utilization_refineries_constraint = Constraint(model.refineries, rule=max_utilization_refineries_constraint_rule)

In [ ]:

# Solve the problem
print("Solution started...")
solver = SolverFactory('ipopt')
results = solver.solve(model)

# Display results
print("Solver status:", results.solver.status)
print("Objective value:", value(model.objective))

In [ ]:

# Display which locations are used as depots
depots_used = [j for j in model.depots if value(model.depots_used[j]) > 0.5]
print("Depot locations:", depots_used)

# Display the harvest flow from each location to each depot
for i in model.locations:
    for j in depots_used:
        flow = value(model.harvest_flow[i, j])
        if flow > 0:
            print(f"Harvest flow from location {i} to depot {j}: {flow}")

# Print locations of used refineries
print("Used Refineries:")
for k in model.refineries:
    if value(model.refineries_used[k]) == 1:
        print(f"Refinery {k}")